- setup.cfg
Now classify `permuta`, `comb_spec_searcher` and `tilings` as first party package. They are therefore all grouped in the same block of import statements
> fix isort import order

- .travis.yml
- tests/algorithms/test_obstruction_inferral.py
- tests/test_tiling.py
- tilings/algorithms/__init__.py
- tilings/algorithms/obstruction_inferral.py
- tilings/tiling.py
Address issue #52 
I'm still working on all obstruction inferral and the tiling methods.
> Obstruction inferral

- tests/fixtures/diverse_tiling.py
- tests/fixtures/no_point_tiling.py
- tests/fixtures/obstructions_requirements.py
- tests/fixtures/simple_tiling.py
- tests/fixtures/simple_trans.py
- tests/strategies/test_batch.py
- tests/strategies/test_decomposition.py
- tests/strategies/test_equivalence.py
- tests/strategies/test_fusion_strat.py
- tests/strategies/test_inferral.py
- tilings/algorithms/__init__.py
- tilings/algorithms/requirement_insertion.py
- tilings/strategies/batch.py
- tilings/strategies/decomposition.py
- tilings/strategies/equivalence.py
- tilings/strategies/fusion.py
- tilings/strategies/inferral.py
- tilings/strategies/verification.py
> Move the strategies to tilings

- tests/algorithms/test_requirement_placements.py
- tilings/algorithms/requirement_placement.py
Fix two problems with `RequirementPlacement`:
> fix partial row and column placements

- tests/algorithms/test_row_col_separation.py
- tests/test_tiling.py
- tilings/algorithms/row_col_separation.py
Consider this tiling:
```
+-+-+
|\| |
+-+-+
|1|1|
+-+-+
1: Av(012)
\: Av+(01)
Crossing obstructions:
10: (0, 1), (0, 0)
021: (0, 0), (0, 1), (1, 0)
Requirement 0:
0: (0, 1)
```
With the current algorithm the separated version is:
```
+-+-+-+
| |\| |
+-+-+-+
|1| |1|
+-+-+-+
1: Av(012)
\: Av+(01)
Crossing obstructions:
01: (0, 0), (2, 0)
Requirement 0:
0: (1, 1)
```
This new separation creates new length 2 obstructions that can be used to
further separates the tiling to:
```
+-+-+-+
| |\| |
+-+-+-+
|1| | |
+-+-+-+
| | |1|
+-+-+-+
1: Av(012)
\: Av+(01)
Requirement 0:
0: (1, 2)
```
This pull request fixes that issue by iterating the separation algorithm until
the given tiling stops changing.
> Make row column separation idempotent.

- tests/algorithms/test_obstruction_inferral.py
- tilings/algorithms/obstruction_inferral.py
- tilings/strategies/__init__.py
- tilings/strategies/inferral.py
- tilings/tiling.py
Adding an strategy to infer any possible obstruction up to a given length.
The `AllObstructionInferral` has changed to reflect the fact that it is not
possible to add obstruction on a tiling without requirements.
> Add ObstructionInferralStrategy

- tests/algorithms/test_enumeration.py
- tests/test_misc.py
- tilings/algorithms/enumeration.py
- tilings/misc.py
I noticed a bug that made this tiling
```
+-+-+-+
|1| | |
+-+-+-+
| |\|\|
+-+-+-+
1: Av+(012)
\: Av(01)
Requirement 0:
0: (0, 1)
```
considered a monotone tree.
The bug was caused by the fact that the `is_tree` function only considered the
edges of the graph. Hence it was unable to spot an isolated vertex has it does
not appear in any edge.
> Consider graph vertices in is_tree function

- tests/test_tilescope.py
- tilings/tilescope.py
There's was a bug with an assertion when trying to start the tilescope
with the tiling that is not 1x1. I moved the asssert so that it's not a
problem anymore.
I also removed the basis function_kwargs as it's not something we use
anymore.
> Fixed a bug when starting the searcher with a tiling.

- tests/algorithms/test_row_col_separation.py
- tests/strategies/test_row_column_separation.py
- tilings/algorithms/row_col_separation.py
- tilings/strategies/row_and_col_separation.py
When row columns separation discovered an empty cell in one of it's
step. It caused a bug when composing the cell maps. This commit fixes by
removing from the final cell maps the cell that are mapped to non-active
cell.
This closes #126
> fix a bug that occurred when composing cell map

- tests/test_tiling.py
- tilings/__init__.py
- tilings/tiling.py
Code that caused error:
[message (24).txt](https://github.com/PermutaTriangle/Tilings/files/4738437/message.24.txt)
The function `_remove_empty_rows_and_cols` was being called when `forward_cell_map` was needed, and the obstructions were being changed.
> Fix a bug where the empty-obstruction Tiling was being modified

- tests/strategies/test_point_placements.py
- tilings/strategies/factor.py
- tilings/strategies/obstruction_inferral.py
- tilings/strategies/requirement_insertion.py
- tilings/strategies/requirement_placement.py
- tilings/strategies/row_and_col_separation.py
This necessary change captures the case when two parent parameters map to the same child parameter, if for example a cell becomes empty. It relies on the corresponding PR on CSS.
> flip extra parameters to be {parent: child}

- CHANGELOG.md
- tests/test_strategy_pack.py
- tilings/strategy_pack.py
- add partial flag to `insertion_point_placements` and
`insertion_row_and_col_placements`
- untracked fusion packs don't add assumption strategies
- the length parameter for `all_the_strategies` is passed correctly to the
requirement insertion strategy.
> Strategy pack options

- CHANGELOG.md
- tilings/strategies/assumption_insertion.py
- tilings/strategies/symmetry.py
Fixes a bug that mean we were never computing all 8 symmetries, just 4 (the rotations). Also fixes a two minor typos I happened to spot.
> Symmetry fix

- CHANGELOG.md
- tilings/strategies/factor.py
- tilings/strategies/fusion.py
- tilings/strategies/obstruction_inferral.py
- tilings/strategies/requirement_insertion.py
- tilings/strategies/requirement_placement.py
- tilings/strategies/symmetry.py
- tilings/tiling.py
This fixes #201 
Before merging, to avoid errors down the line, we should create a method `forward_map_assumption` on `Tiling` as this particular snippet is the same in several strategies (e.g., req insertion) and apparently every time I need it, I forget this tiny detail!
> refactor assumption mapping code

- CHANGELOG.md
- tests/test_tiling.py
- tilings/tiling.py
Removes some pylint errors, and moves failures to local to the function which have them. 
This is in response to issue #144
> pylint fixes in tiling.py

- CHANGELOG.md
- tests/algorithms/test_fusion.py
- tilings/algorithms/fusion.py
- only fuse non-empty regions to avoid creating unintentional rules a -> b
where a and b are equivalent
> Fuse non empty regions

- CHANGELOG.md
- tests/test_tilescope.py
- tilings/algorithms/factor.py
- tilings/algorithms/fusion.py
- tilings/assumptions.py
- tilings/strategies/__init__.py
- tilings/strategies/detect_components.py
- tilings/strategy_pack.py
- tilings/tiling.py
- `remove_components_from_assumptions` method to `Tiling`
- `DetectComponentsStrategy` which removes cells from assumptions
which are actual components. This replaces the need for the
`SplittingStrategy` in component fusion packs.
- forbid fusing a region containing a `TrackingAssumption` and a
`ComponentAssumption`
- a tiling factors if a `ComponentAssumption` if the components of the region
split into the factors
> Component tracking

- CHANGELOG.md
- tests/strategies/test_factors.py
- tests/test_tiling.py
- tilings/strategies/assumption_insertion.py
- tilings/strategies/factor.py
- tilings/tiling.py
- remove duplicate assumptions in the `AddAssumptionsStrategy`
- `Tiling.from_dict` will make a `Tiling` with no assumptions if the
`assumptions` key is not in the dictionary.
- a factor with interleaving strategy has `inferrable=True`
> Add assumptions bug

- CHANGELOG.md
- README.rst
- setup.py
- tests/strategies/test_factors.py
- tests/strategies/test_fusion_strat.py
- tests/test_assumptions.py
- tests/test_tilescope.py
- tilings/strategies/assumption_insertion.py
- tilings/strategies/assumption_splitting.py
- tilings/strategies/factor.py
- tilings/strategies/fusion.py
- the `get_eq_symbol` and `get_op_symbol` are moved to `Strategy` rather than
`Constructor`
- untracked constructors raise `NotImplementedError`
> Update to CSS 2.0.0

- tests/strategies/test_row_column_separation.py
This test will fail due to a small change in the error string that is returned. The type of error staying the same is all we should check in my opinion.
> remove error string test

- CHANGELOG.md
- tilings/strategies/fusion.py
The `isolation_level` parameter was not being passed into the component fusion algo class.
> fix isolation level issue on component fusion

- CHANGELOG.md
- tilings/algorithms/fusion.py
@enadeau: We will now add rules from fusion which are empty cell inferral after this is added? Will the fusion rule make them 'equivalent'? Will CSS favour the empty cell inferral which may happen later?
@jaypantone this was originally added due to a bug you found when running
```
This must be all_the_strategies(2)?
Found specification for 0123_0231_3012 with all_the_strategies_fusion_isolated_single_fusion  of size 42 in 6:20:32.
Enumeration: Counting or sending message or writing failed: maximum recursion depth exceeded
```
could you do run again to see if the issue persists after removing this check?
> removed redundant is empty check in fusion algorithm

- tests/algorithms/test_fusion.py
- tilings/algorithms/fusion.py
If you call the min number of point on the fusion algorithm before checking if
it is fusable you get an incorrect answer. Just added the failing test for now
but will fix after merging reverse fusion
> Invalid min point for fusion algo

- tests/strategies/old_rule_json.jsonl
- tests/strategies/test_json_encoding.py
- tilings/strategies/verification.py
This introduces a new series of test where we make sure we don't brake backward
compatibility with JSON.
When we run into a backward compatibility problem we can add the JSON to the new
file to get it tested.
> Old strategy JSON

- tests/strategies/test_verification.py
- tilings/algorithms/locally_factorable_shift.py
- tilings/strategies/verification.py
I've changed the locally factorable shift computation to rely on the expansion instead of the subobstruction inferral. To speed up the computation of the shift I've created a verification strategy that verifies any tiling that doesn't have a cell that is the root. This will reduce the amount of expansion needed to compute the shifts and the children.
> shifts locally factorable

- tests/test_tiling.py
- tilings/algorithms/__init__.py
- tilings/algorithms/map.py
- tilings/algorithms/row_col_separation.py
- tilings/assumptions.py
- tilings/misc.py
- tilings/strategies/factor.py
- tilings/strategies/fusion/fusion.py
- tilings/strategies/obstruction_inferral.py
- tilings/strategies/requirement_insertion.py
- tilings/strategies/requirement_placement.py
- tilings/tiling.py
We should probably consider moving the map class to another file. I think we
could probably use the same class for the map between tiling and assumption.
> New tiling init map

- tilings/map.py
> Remove unnecessary method redefintion

- CHANGELOG.md
- tilings/strategies/symmetry.py
- tilings/strategy_pack.py
Takes into account the basis. Will only return symmetric tilings if all the patts are subpatterns of some basis element.
> Selective symmetries

- tests/test_tilescope.py
Now that we do strategic garbage collection in some of our code some
test where timing out because the gc.collect() call where taking to
long. I introduced a new decorator to collect before those test to avoid
triggering out the timeout.
> New collect_before decorator for some test.

- CHANGELOG.md
- tilings/strategies/assumption_insertion.py
this partially addresses issue #455
> add assumption reversible when assumption covers whole tiling

- CHANGELOG.md
- tilings/strategies/requirement_insertion.py
Testing plan: after merging the PR to show number of rules produced per strategy, try some runs with and without factorable requirement insertions, to see how much the universe is expanded.
> adds flag to allow factorable requirement insertions, default = False

- CHANGELOG.md
- tests/strategies/test_sliding.py
- tilings/strategies/monotone_sliding.py
Previous broken rules will now raise `StrategyDoesNotApply` when calling the decomposition function.
> check in decomp func of sliding

- tilings/strategies/verification.py
Will require an update on CSS to work.
> fix k0 / k_0 typo in 1x1 eqs

- CHANGELOG.md
- tilings/algorithms/locally_factorable_shift.py
`shift_from_spec` method would previously fail if any tiling had two or more interleaving cells.
> Shift from spec
