PermutaTriangle/Tilings

- CHANGELOG.md
- setup.py
- tilings/griddedperm.py
This is ready to go. Before merging, we just need to wait that permuta release the needed feature
> optimize containment test for gridded perm

- tests/algorithms/test_fusion.py
- tests/test_tiling.py
- tilings/algorithms/__init__.py
- tilings/algorithms/fusion.py
- tilings/tiling.py
> Component fusion

- tests/strategies/test_batch.py
- tests/strategies/test_decomposition.py
- tests/strategies/test_equivalence.py
- tests/strategies/test_fusion_strat.py
- tests/strategies/test_inferral.py
- tests/strategies/test_json_encoding.py
- tilings/algorithms/__init__.py
- tilings/algorithms/requirement_insertion.py
- tilings/strategies/__init__.py
- tilings/strategies/abstract_strategy.py
- tilings/strategies/batch.py
- tilings/strategies/decomposition.py
- tilings/strategies/equivalence.py
- tilings/strategies/fusion.py
- tilings/strategies/inferral.py
- tilings/strategies/verification.py
Pull request to transform all the strategies into callable classes
> Strategy as class

- tests/strategies/test_json_encoding.py
- tests/test_strategy_pack.py
- tests/test_tilescope.py
- tilings/algorithms/requirement_placement.py
- tilings/strategies/abstract_strategy.py
- tilings/strategies/batch.py
- tilings/strategies/equivalence.py
- tilings/strategies/fusion.py
- tilings/strategies/verification.py
- tilings/strategy_pack.py
- tilings/tilescope.py
This pull request closes #57 and closes #59
> Implementing strategy pack

- tests/algorithms/test_requirement_placements.py
- tests/strategies/test_json_encoding.py
- tests/test_strategy_pack.py
- tests/test_tilescope.py
- tilings/algorithms/requirement_placement.py
- tilings/strategies/abstract_strategy.py
- tilings/strategies/batch.py
- tilings/strategies/equivalence.py
- tilings/strategies/fusion.py
- tilings/strategies/verification.py
- tilings/strategy_pack.py
- tilings/tilescope.py
> Add an option to restrict direction in requirement placement

- tilings/strategies/batch.py
- tilings/strategy_pack.py
I allowed insertion in tiling with requirements for the root insertion strategy in order to achieve root requirements extension.
@ulfarsson  and @christianbean Do we still want a pack that also has requirement extension in it?
> Root placement pack

- tests/algorithms/test_requirement_insertion.py
- tests/strategies/test_batch.py
- tests/strategies/test_json_encoding.py
- tilings/algorithms/requirement_insertion.py
- tilings/strategies/batch.py
- tilings/strategy_pack.py
This pull request fix the bug that only inserted lexicographically bigger
permutation in cell.
It also adds the option to restrict the number of requirement that can be
inserted in a single cell.
> Root insertion bug

- tests/algorithms/test_enumeration.py
- tilings/algorithms/enumeration.py
This pull request aims at improving the monotone tree enumeration algorithm in two ways
1. Handle monotone cell that are finite
2. Handle localized requirement on the tiling.
> Monotone tree

- CHANGELOG.md
- tilings/algorithms/__init__.py
- tilings/algorithms/gridded_perm_generation.py
- tilings/griddedperm.py
- tilings/tiling.py
> Improving gridded perm generation

- tests/strategies/test_verification.py
- tests/test_tilescope.py
- tilings/algorithms/requirement_placement.py
- tilings/strategies/factor.py
- tilings/strategies/fusion.py
- tilings/strategies/obstruction_inferral.py
- tilings/strategies/requirement_insertion.py
- tilings/strategies/requirement_placement.py
- tilings/strategies/row_and_col_separation.py
- tilings/strategies/symmetry.py
- tilings/strategies/verification.py
- tilings/strategy_pack.py
- tilings/tiling.py
This also fixes the fact direction wasn't passed in reg ins encoding strategy
Includes a test for a regular insertion encoding class, sampling, and counting objects
> image of bijection is Tuple[Optional[GriddedPerm], ...]

- tests/algorithms/test_factor.py
- tests/algorithms/test_requirement_placements.py
- tests/test_assumptions.py
- tilings/algorithms/enumeration.py
- tilings/algorithms/factor.py
- tilings/algorithms/fusion.py
- tilings/algorithms/requirement_placement.py
- tilings/algorithms/row_col_separation.py
- tilings/assumptions.py
- tilings/strategies/__init__.py
- tilings/strategies/assumption_splitting.py
- tilings/strategies/fusion.py
- tilings/strategies/symmetry.py
- tilings/strategy_pack.py
- tilings/tiling.py
Added an AbstractAssumtpion class.
In particular a `TrackingAssumption`, which will keep track of a set of gridded permutations.
> Assumptions

- tests/algorithms/test_minimal_gridded_perms.py
- tilings/algorithms/minimal_gridded_perms.py
Sometime some the Minimal Gridded Perm algorithm was not returning the
gps in increasing length order. This is now fixed
> fix a bug in the ordering of the mgps

- tests/strategies/test_requirement_insertions.py
- tests/strategies/test_row_column_separation.py
- tests/test_tiling.py
- tilings/algorithms/__init__.py
- tilings/algorithms/factor.py
- tilings/algorithms/gridded_perm_reduction.py
- tilings/algorithms/requirement_placement.py
- tilings/algorithms/row_col_separation.py
- tilings/strategies/requirement_insertion.py
- tilings/strategies/symmetry.py
- tilings/tilescope.py
- tilings/tiling.py
This moves some of the code in the initialiser from Tiling to an algorithm class
> init algorithm

- tests/strategies/test_row_column_separation.py
- tilings/algorithms/row_col_separation.py
> need to simplify when finding cell maps

- tests/algorithms/test_enumeration.py
- tests/strategies/test_verification.py
- tests/test_tilescope.py
- tilings/algorithms/enumeration.py
- tilings/strategies/verification.py
I've added the no factors option a to the expansion pack and set up a test to check that. However the test is failing because with cPython it does not expand for some reason.
> No factor in expansions

- tests/test_strategy_pack.py
- tilings/strategies/requirement_placement.py
- tilings/strategy_pack.py
> Update root pack

- tests/algorithms/test_enumeration.py
- tests/strategies/test_verification.py
- tests/test_assumptions.py
- tests/test_tilescope.py
- tests/test_tiling.py
- tilings/algorithms/enumeration.py
- tilings/strategies/requirement_placement.py
- tilings/strategies/verification.py
- tilings/strategy_pack.py
Try to expand verified classes with packs that we know will succeed in enumerating the class in terms of atoms.
> Expanding locally verified objects

- tests/strategies/test_row_column_separation.py
- tilings/strategies/row_and_col_separation.py
> remove assumptions if use a cell that becomes empty

- README.rst
- tilings/griddedperm.py
an ascii plot method
I used this in the readme for an example, and for visualising the sampling etc.
> Ascii plot

- tests/strategies/test_fusion_strat.py
- tilings/strategies/fusion.py
- tilings/tiling.py
> Fuse param bug

- tilings/strategies/assumption_insertion.py
- tilings/strategies/fusion.py
tiny optimisation in fusion enumeration
> raise strategy does not apply error if assumption on tiling already.

- CHANGELOG.md
- tests/strategies/test_verification.py
- tilings/algorithms/enumeration.py
- tilings/strategies/verification.py
This fixes #190 and #187, so closing PR #188 which also fixed #187.
> No more class to expand error

- CHANGELOG.md
- tilings/strategies/fusion.py
- tilings/tiling.py
- fix assumption mapping bug in `FusionStrategy`
- fix `__repr__` in `FusionStrategy`
fixes #199 
added bugged rule to sanity check branch
> map assumptions in fusion strategy with child forward map

- CHANGELOG.md
- setup.py
- tests/strategies/sanity_checking_rules.py
- tests/strategies/test_sanity_check.py
- tilings/tiling.py
This relies on the PR sanity check multiple variables #147 on CSS. Will need to wait on a release therefore.
> Sanity check rules

- CHANGELOG.md
- tilings/strategies/fusion.py
> ignore empty assumptions when mapping

- CHANGELOG.md
- tests/algorithms/test_enumeration.py
- tests/strategies/test_verification.py
- tilings/algorithms/enumeration.py
- tilings/strategies/verification.py
- tilings/tiling.py
- the method `Tiling.get_genf` returns the Catalan generating function for Av(123).
> get genf returns catalan for Av(123)

- CHANGELOG.md
- tests/strategies/test_assumtions_splitting.py
- tilings/strategies/assumption_splitting.py
> Fix generating function for splitting strategy

- CHANGELOG.md
- tilings/strategies/assumption_insertion.py
- tilings/strategies/assumption_splitting.py
- tilings/strategies/factor.py
- tilings/strategies/fusion.py
Relies on the next version of CSS.
> add can_be_equivalent methods

- tox.ini
Reverts PermutaTriangle/Tilings#219
> Revert "[requires.io] dependency update on develop branch"

- CHANGELOG.md
- README.rst
- tests/strategies/test_verification.py
- tilings/algorithms/factor.py
- tilings/assumptions.py
- tilings/strategies/factor.py
- tilings/strategies/verification.py
- tilings/strategy_pack.py
- tilings/tiling.py
this means we can skip the splitting strategy.
> factor assumptions inside the factor strategy

- CHANGELOG.md
- tests/strategies/test_json_encoding.py
- tilings/strategies/requirement_insertion.py
- tilings/strategy_pack.py
- added the `one_cell_only` option to `CellInsertionFactory`
- insertion packs now use the `one_cell_only` option
> add one cell only flag to CellInsertionFactory

- CHANGELOG.md
- tests/strategies/test_fusion_strat.py
- tilings/strategies/fusion.py
Enables fusion equations when one or both of the fusing cells is positive.
> Positive fusion eqs

- CHANGELOG.md
- tests/test_strategy_pack.py
- tilings/strategy_pack.py
removed the length argument to the `insertion_point_placements` pack which was not implemented, and thus raising an error.
fixes #241
> Remove length

- CHANGELOG.md
- README.rst
- tests/test_tilescope.py
- tilings/algorithms/__init__.py
- tilings/algorithms/gridded_perm_generation.py
- tilings/algorithms/minimal_gridded_perms.py
- tilings/tiling.py
- the `GriddedPermsOnTiling` algorithm was changed to build from minimal
gridded perms in a breadth first manner. This is also include an option to
limit the number of points placed on the minimal gridded perms.
> Gridded perm generation

- CHANGELOG.md
- tilings/strategy_pack.py
- tilings/tiling.py
- combines the expansion strategies of most packs into a single expansion set
- adds the point_and_row_and_col_placements strategy that has proved useful in the last 2x4 and several forests
> Strat pack changes

- tests/strategies/test_verification.py
- tilings/strategies/verification.py
I would be nice to get be able to get the generation function for 1x1 with assumption. I've started doing it but the problem is a bit more involved than I expected so I have the test but still need to do find the fix.
> Generating function for 1x1 with assumptions

- tests/test_assumptions.py
- tilings/assumptions.py
> Fix assumption ordering

- tests/strategies/test_sanity_check.py
- tilings/strategies/fusion/constructor.py
> fusion with non contiguous assumption is allowed

- tests/strategies/test_json_encoding.py
- tilings/strategies/rearrange_assumption.py
> fix json encoding of rearrange strategy

- CHANGELOG.md
- tests/strategies/test_sanity_check.py
- tests/test_assumptions.py
- tests/test_temp.py
- tilings/strategies/rearrange_assumption.py
> test that rules and spec a picklable

- tests/strategies/test_encoding.py
- tilings/strategies/assumption_splitting.py
- tilings/strategies/experimental_verification.py
- tilings/strategies/factor.py
- tilings/strategies/obstruction_inferral.py
- tilings/strategies/rearrange_assumption.py
- tilings/strategies/requirement_insertion.py
- tilings/strategies/requirement_placement.py
- tilings/strategies/verification.py
Depends on PermutaTriangle/comb_spec_searcher/pull/276
> Fix all the strategy repr

- tests/test_tilescope.py
Remove the test for the limited strategy as it will be removed from css
> Remove limited ruledb test

- CHANGELOG.md
- README.rst
- tests/test_tilescope.py
- tilings/algorithms/locally_factorable_shift.py
- tilings/strategies/verification.py
- use the returned expanded spec in test
- fix one by one strategy for locally factorable
- fix readme test
- fix test that verified positive root
> fix expansion

- tests/test_assumptions.py
- tests/test_tiling.py
- tilings/algorithms/__init__.py
- tilings/algorithms/map.py
- tilings/algorithms/row_col_separation.py
- tilings/assumptions.py
- tilings/misc.py
- tilings/strategies/assumption_splitting.py
- tilings/strategies/factor.py
- tilings/strategies/fusion/fusion.py
- tilings/strategies/obstruction_inferral.py
- tilings/strategies/requirement_insertion.py
- tilings/strategies/requirement_placement.py
- tilings/strategies/verification.py
- tilings/tiling.py
- fix test that use expand_verified
- Make the forward tiling map a class
- add documentation
- add a map_row and map_column method
- update row map
- fixing stuff I'm not sure I understand
- remove dead stuff
- good way to get preimage for grinding counter
- Revert "fixing stuff I'm not sure I understand"
- remove some sum/skew import that no longer make sense
- add remove requirements on tiling
- fix a sort assumption not existing function
- fix assumption map update
- New tiling init map (#350)
> Update tilings-assumption with develop

- mypy.ini
- tests/algorithms/test_row_col_separation.py
- tilings/algorithms/row_col_separation.py
- tilings/map.py
- tilings/parameter_counter.py
- tilings/strategies/row_and_col_separation.py
- tilings/tiling.py
- typing rcs algo
- introducing the cell map class
- use the CellMap class in row col sep algorithm
- add map_tiling method
- allow crossing map for preimage counter
- map preimage counter
- make param counter iterable
- implement map parameters
- map inverse method and to_row_col_map
- simplify projection computation
- move param mapping stuff to the map class
- fix the strategy
> Row columns separation strategy

- tests/strategies/test_sanity_check.py
A test that passes once the PR on CSS is merged.
https://github.com/PermutaTriangle/comb_spec_searcher/pull/312
> adding a test

- tests/test_parameter_rule.py
- tilings/algorithms/fusion.py
- tilings/strategies/fusion/constructor.py
- handle positive fusion with new param
- prevent fusion when out of bound
> Positive fusion and fusion out of bound

- tests/test_assumptions.py
- tests/test_parameter_rule.py
- tilings/strategies/parameter_strategies.py
- Change the remove req factory
- test that we get hennings weird 123 tree
> Rectrictin the removal of preimage req strategy

- tests/test_parameter_rule.py
- tilings/algorithms/fusion.py
- tilings/parameter_counter.py
- tilings/strategies/parameter_strategies.py
- tilings/tiling.py
- sort input when adding a parameters
- more fine grain control on fusion and relaxing fuse condition
- add always_count_one for preimage
- smarter remove req factory
> restricting fusion

- CHANGELOG.md
- setup.py
- tilings/tilescope.py
- tox.ini
We now create a new `TrackedQueue`. The idea is this is a list of queues, and when a label is added it is added to the same queue that the underlying label was added to.
> a new approach to tracked searcher!

- .pre-commit-config.yaml
- CHANGELOG.md
- tests/algorithms/test_enumeration.py
- tests/strategies/test_verification.py
- tests/test_tiling.py
- tilings/algorithms/enumeration.py
- tilings/algorithms/requirement_placement.py
- tox.ini
This was previously inferred by obstruction transitivity, but we can instead do it earlier to save builidng that intermediate tiling.
> add empty cell obs during placement

- tests/strategies/test_encoding.py
- tests/strategies/test_verification.py
- tilings/strategies/__init__.py
- tilings/strategies/experimental_verification.py
- tilings/tilescope.py
> No Root Cell verification

- tests/algorithms/test_fusion.py
- tilings/algorithms/fusion.py
- tilings/algorithms/sliding.py
- tilings/strategies/assumption_splitting.py
- tilings/tiling.py
I propose removing the failing test. It was testing that you could get the fused tiling for non-fusable tilings. Do we even want this?
This addresses issue #147
> adding init flags

- CHANGELOG.md
- tilings/algorithms/gridded_perm_reduction.py
- tilings/algorithms/minimal_gridded_perms.py
- tilings/strategy_pack.py
- tilings/tiling.py
Do the potentially large product in a smarter way.  
Also includes the change to the pattern placement pack.
> Improving initialiser

- .pre-commit-config.yaml
- tilings/strategies/factor.py
- tox.ini
> make not implemented reverse constructor for interleaving factor

- CHANGELOG.md
- tilings/strategies/__init__.py
- tilings/strategies/assumption_insertion.py
- tilings/strategies/factor.py
- tilings/strategy_pack.py
Instead, the factor strategy now implicitly does an AddAssumptionStrategy in the background.
> remove AddInterleavingAssumptionsFactory

- tests/strategies/test_encoding.py
- tilings/strategies/factor.py
> fix json and repr encoding of interleaving factor strategy

- tilings/strategies/pointing.py
- tilings/strategy_pack.py
- tilings/tilescope.py
Testing plan: Test with PR that shows # of rules produced, and compare universe sizes with different default values of the flags (including set high enough to have no effect)
> more flags for pointing

- CHANGELOG.md
- tests/strategies/test_sliding.py
- tilings/strategies/monotone_sliding.py
Adds missing consecutive value condition for monotone sliding.
> Sliding bug

- CHANGELOG.md
- tests/test_strategy_pack.py
- tilings/strategies/__init__.py
- tilings/strategies/requirement_insertion.py
- tilings/strategy_pack.py
`BasisPatternInsertionFactory` which inserts permutations which are contained in
every pattern in the basis
Use StrategyPack.basis_pattern_insertions
> a new pack

- CHANGELOG.md
- tilings/strategies/monotone_sliding.py
- tilings/strategies/point_jumping.py
> fix misc bugs in kitchen sink strategies
